# Generated by Django 4.2.5 on 2023-10-15 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_img', '0002_carosel1_carosel2_carosel3_delete_admin_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('img_url', models.URLField()),
                ('status', models.TextField(default='Carousel')),
            ],
        ),
        migrations.DeleteModel(
            name='Carosel1',
        ),
        migrations.DeleteModel(
            name='Carosel2',
        ),
        migrations.DeleteModel(
            name='Carosel3',
        ),
    ]
