# Generated by Django 4.2.5 on 2023-10-15 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_img', '0003_carousel_delete_carosel1_delete_carosel2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Static_img',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('img_url', models.URLField()),
                ('status', models.TextField(default='Static')),
            ],
        ),
    ]
