# Generated by Django 4.2.5 on 2023-10-14 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rboards', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Article',
            new_name='Rboard',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='origin_article',
            new_name='origin_rboard',
        ),
    ]
