# Generated by Django 4.2.5 on 2023-10-18 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rboards', '0002_comment_comment_disliked_users_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rboard',
            name='img_url',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
