# Generated by Django 4.2.5 on 2023-10-18 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rboards', '0003_rboard_img_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='rboard',
            name='status',
            field=models.TextField(default='Rboard'),
        ),
    ]
