# Generated by Django 4.2.5 on 2023-10-15 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lunch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('menuCourseType', models.CharField(max_length=5)),
                ('main_menu', models.CharField(max_length=50)),
                ('sub_menu', models.CharField(max_length=50)),
                ('kcal', models.IntegerField()),
                ('carb', models.IntegerField()),
                ('sodium', models.IntegerField()),
                ('fat', models.IntegerField()),
                ('protein', models.IntegerField()),
                ('image_url', models.URLField()),
            ],
        ),
    ]
