# Generated by Django 4.2.5 on 2023-10-15 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lunch',
            old_name='carb',
            new_name='carbs',
        ),
    ]
