# Generated by Django 4.2.5 on 2023-10-17 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_rename_carb_lunch_carbs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lunch',
            name='carbs',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='lunch',
            name='fat',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='lunch',
            name='kcal',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='lunch',
            name='protein',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='lunch',
            name='sodium',
            field=models.CharField(max_length=10),
        ),
    ]
