# Generated by Django 4.2.5 on 2023-09-19 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_alter_article_created_at_alter_comment_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='visited_count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
