# Generated by Django 4.2.5 on 2023-09-24 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_article_visited_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='textcolor',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='textsize',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
