# Generated by Django 4.2.5 on 2023-09-24 22:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_remove_article_textcolor_remove_article_textsize'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='textcolor',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='textsize',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
