# Generated by Django 4.2.5 on 2023-10-14 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_article_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='img_url',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='status',
            field=models.TextField(default='Article'),
        ),
    ]
