# Generated by Django 4.2.5 on 2023-10-14 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0011_article_user_comment_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='user',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
    ]
