# Generated by Django 4.2.5 on 2023-10-14 23:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0012_remove_article_user_remove_comment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='disliked_users',
            field=models.ManyToManyField(related_name='disliked_articles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='article',
            name='liked_users',
            field=models.ManyToManyField(related_name='liked_articles', to=settings.AUTH_USER_MODEL),
        ),
    ]
