# Generated by Django 4.2.5 on 2023-10-16 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_article_img_url_article_status'),
        ('articles', '0015_rename_disliked_users_comment_comment_disliked_users_and_more'),
    ]

    operations = [
    ]
