# Generated by Django 4.2.5 on 2023-10-18 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0016_merge_20231016_1308'),
        ('articles', '0017_choice_poll_vote_choice_poll'),
    ]

    operations = [
    ]
