# Generated by Django 4.2.5 on 2023-10-26 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0016_merge_20231016_0542'),
        ('articles', '0018_merge_20231018_0215'),
    ]

    operations = [
    ]
