# Generated by Django 4.2.5 on 2023-10-26 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0019_merge_20231026_2049'),
        ('articles', '0019_merge_20231026_2054'),
        ('articles', '0019_merge_20231026_2101'),
    ]

    operations = [
    ]
